### ISSUE TITLE
[BUG] Unable to generate PDF file

### ISSUE THREAD

**Issue by timurguvenkaya** [Sparticuz/chromium#148]
## Environment

- `chromium` Version: 116.0.0
- `puppeteer` / `puppeteer-core` Version: 21.1.0
- Node.js Version:  18.x
- Lambda / GCF Runtime:  nodejs18.x

## Expected Behavior

PDF should be generated

## Current Behavior

I manually created a layer through the AWS console and added arn to serverless. 

I'm getting this error when I try to generate pdf with .pdf()

```
TypeError: t is not a constructor
    at ME (webpack:///puppeteer-core/lib/esm/puppeteer/common/util.js:451:12)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9)
    at u4.pdf (webpack:///puppeteer-core/lib/esm/puppeteer/common/Page.js:944:26)
    at Runtime.RY (webpack:///apps/api/src/handlers/bucket/upload.ts:100:24)
```
```typescript
                                 const execPath = await chromium.executablePath();

                                 const browser = await puppeteer.launch({
					args: chromium.args,
					userDataDir: '/tmp',
					defaultViewport: chromium.defaultViewport,
					executablePath: execPath,
					headless: chromium.headless,
					ignoreHTTPSErrors: true,
				});

				const page = await browser.newPage();

				await page.goto(reportUrl, {
					waitUntil: ['networkidle0', 'domcontentloaded'],
				});

				console.log('Chromium:', await browser.version());
				console.log('Page Title:', await page.title());

				await page.emulateMediaType('screen');

				const webPagePdf = await page.pdf(); // Error here

				console.log('PAGE_PDF: ', webPagePdf);

				await page.close();

				await browser.close();
``` 

serverless.yml

```yaml
uploadFunction:
    runtime: nodejs18.x
    handler: src/handlers/bucket/upload.handler
    events:
      - httpApi:
          path: /upload-report
          method: POST
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
        Resource:
          - "arn:aws:s3:::${self:custom.uploadBucketName}/*"
    layers:
      - arn:aws:lambda:us-east-1:************:layer:chromium:*
```

## Steps to Reproduce

Try generating a pdf with some URL as in my code.

## Possible Solution

Would love to get some tips what can be an issue
