### ISSUE TITLE
[BUG] Cannot find chromium when building for serverless with layers

### ISSUE THREAD

**Issue by aaronbannin** [Sparticuz/chromium#150]
## Environment

- `chromium` Version: `@sparticuz/chromium@116.0.0`
- `puppeteer` / `puppeteer-core` Version: `puppeteer-core@21.1.1`
- Node.js Version:  `v18.17.0`
- Lambda / GCF Runtime:  `nodejs18.x`

## Expected Behavior
When running `sls deploy`, `chromium.executablePath()` should resolve to the Lambda layer not local project.

## Current Behavior

When running `sls deploy`, the following error is thrown (paths are converted to relative):

Running `sls invoke local` succeeds (see `puppeteer.launch()` method below).

```
Error:
[OperationalError: ENOENT: no such file or directory, open '~/.serverless/chromium.zip'] {
  cause: [Error: ENOENT: no such file or directory, open '~/.serverless/chromium.zip'] {
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path: '~/.serverless/chromium.zip'
  },
  isOperational: true,
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '~/.serverless/chromium.zip'
}
```

## Steps to Reproduce
Used [serverless-with-lambda-layer](https://github.com/Sparticuz/chromium/tree/master/examples/serverless-with-lambda-layer) as a reference.

`serverless.yml`
```
functions:
  main:
    handler: src/main.handler
    maximumRetryAttempts: 0
    layers:
      - !Ref ChromiumtestLambdaLayer

layers:
  chromiumtest:
    package:
      artifact: ../../chromium/chromium.zip
```

In `main.ts`:
```  
const browser = await puppeteer.launch({
    args: process.env.IS_LOCAL ? puppeteer.defaultArgs() : chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: process.env.IS_LOCAL
      ? browserPath
      : await chromium.executablePath(),
    headless: chromium.headless,
    ignoreHTTPSErrors: true,
  });
```
