### ISSUE TITLE
[BUG] chromium binary not uploaded to lambda function via SAM template

### ISSUE THREAD

**Issue by casertap** [Sparticuz/chromium#167]
Potentially something missing in the documentation.

## Environment

packages.json
```
    "dependencies": {
        "@sparticuz/chromium": "112",
        "puppeteer-core": "19.8.0",
    },
```
template.yaml
```
Globals:
  Function:
    Architectures:
      - x86_64
    MemorySize: 512
    Runtime: nodejs18.x
    Timeout: 30
...
Resources:
  HandlerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: cjs
        Minify: false
        Target: "es2022"
        EntryPoints: 
        - src/handler.ts

```

## Expected Behavior

Only one js file called handler.js is uploaded to my aws lambda function and so I am getting the error bellow
```
2023-10-21T00:05:56.255Z	87fb1c51-ee93-5e75-9487-41fcf68928db	INFO	Error: The input directory "/var/bin" does not exist.
    at Chromium.executablePath (/var/task/handler.js:59727:17)
    at Runtime.handler (/var/task/handler.js:85213:63)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29
```

## Current Behavior

Instead I would like the chromium binary to be available somewhere in my lambda function on aws 

## Steps to Reproduce
```
sam deploy 
```
with the settings provided

**Comment by casertap** [comment]
I decided to add the layer corresponding to my corresponding version
```
Resources:
  Chromium112LambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: chromium-v112-0-2-layer
      Description: chromium-v112.0.2-layer
      ContentUri: ./layers/chromium-v112.0.2-layer.zip
      CompatibleRuntimes: 
        - nodejs18.x
      CompatibleArchitectures: 
        - x86_64
```

now this still fail on aws `await chromium.executablePath()` so I created this code
```
    const executablePath = local ? await chromium.executablePath() : "/opt/nodejs/node_modules/@sparticuz/chromium";
```
I am now getting another kind of error (NOTE `await chromium.executablePath()` is not called anymore)
```
Error: Failed to launch the browser process! spawn /opt/nodejs/node_modules/@sparticuz/chromium EACCES
```

though the settings are:
```
{
    "args": [
        "--allow-pre-commit-input",
        "--disable-background-networking",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-breakpad",
        "--disable-client-side-phishing-detection",
        "--disable-component-extensions-with-background-pages",
        "--disable-component-update",
        "--disable-default-apps",
        "--disable-dev-shm-usage",
        "--disable-extensions",
        "--disable-hang-monitor",
        "--disable-ipc-flooding-protection",
        "--disable-popup-blocking",
        "--disable-prompt-on-repost",
        "--disable-renderer-backgrounding",
        "--disable-sync",
        "--enable-automation",
        "--enable-blink-features=IdleDetection",
        "--export-tagged-pdf",
        "--force-color-profile=srgb",
        "--metrics-recording-only",
        "--no-first-run",
        "--password-store=basic",
        "--use-mock-keychain",
        "--disable-domain-reliability",
        "--disable-print-preview",
        "--disable-speech-api",
        "--disk-cache-size=33554432",
        "--mute-audio",
        "--no-default-browser-check",
        "--no-pings",
        "--single-process",
        "--disable-features=Translate,BackForwardCache,AcceptCHFrame,MediaRouter,OptimizationHints,AudioServiceOutOfProcess,IsolateOrigins,site-per-process",
        "--enable-features=NetworkServiceInProcess2,SharedArrayBuffer",
        "--hide-scrollbars",
        "--ignore-gpu-blocklist",
        "--in-process-gpu",
        "--window-size=1920,1080",
        "--use-gl=angle",
        "--use-angle=swiftshader",
        "--allow-running-insecure-content",
        "--disable-setuid-sandbox",
        "--disable-site-isolation-trials",
        "--disable-web-security",
        "--no-sandbox",
        "--no-zygote",
        "--headless='new'"
    ],
    "defaultViewport": {
        "deviceScaleFactor": 1,
        "hasTouch": false,
        "height": 1080,
        "isLandscape": true,
        "isMobile": false,
        "width": 1920
    },
    "executablePath": "/opt/nodejs/node_modules/@sparticuz/chromium",
    "headless": "new",
    "ignoreHTTPSErrors": true
}
```
