### ISSUE TITLE
AutoSelectCertificateForUrls policy

### ISSUE THREAD

**Issue by sbalbinot** [Sparticuz/chromium#175]
Hi there! I am currently in the process of building a web scraper in AWS Lambda using Node.js, Puppeteer, Docker image and AWS SAM. This particular scraper requires authentication via a Client Certificate on a website (initially testing with the badssl website). I have successfully downloaded the certificate file from S3 and built the NSSDB to be used in Chromium. However, I am now faced with the challenge of creating an 'AutoSelectCertificateForUrls' policy to prevent the authentication dialog from prompting. I attempted to create the '/etc/chromium/policies/managed/auto_select_certificate.json' file, but it seems that Chromium is not recognizing it (I'm pulling it from a layer). I am wondering if it is possible to define this type of policy for Chromium using this particular package?

AWS SAM Template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  esocial-aws

  Sample SAM Template for esocial-aws
  
Globals:
  Function:
    Timeout: 60
    MemorySize: 2048

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Sub 'arn:aws:lambda:sa-east-1:764866452798:layer:chrome-aws-lambda:38'
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

```

Dockerfile:

```dockerfile
FROM public.ecr.aws/lambda/nodejs:18

ARG HOME=/tmp

ENV HOME=${HOME}

RUN mkdir -p ${HOME}/.pki/nssdb
RUN certutil -N --empty-password -d sql:$HOME/.pki/nssdb
RUN mkdir -p /etc/chromium/policies/managed/
RUN echo '{"AutoSelectCertificateForUrls": ["{\"pattern\":\"*\",\"filter\":{\"ISSUER\":{\"CN\":\"BadSSL Client Root Certificate Authority\""}"}}"]}' > /etc/chromium/policies/managed/auto_select_certificate.json

COPY app.mjs package*.json ./

RUN npm install

CMD ["app.lambdaHandler"]
```

Lambda handler:

```javascript
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3'
import { createWriteStream, readdirSync } from 'fs'
import { promisify } from 'util'
import chromium from '@sparticuz/chromium'
import puppeteer from 'puppeteer-core'


export const lambdaHandler = async (event, context) => {
    try {
        const exec = promisify((await import('child_process')).exec)
        const { HOME } = process.env
        const bucketName = 'sample-bucket'
        const certificateKey = 'badssl.com-client.p12'
        const certificatePassword = 'badssl.com'

        const bucket = new S3Client()
        const { Body } = await bucket.send(new GetObjectCommand({ Bucket: bucketName, Key: certificateKey }))

        await new Promise((resolve, reject) => {
            Body.pipe(createWriteStream(`${HOME}/${certificateKey}`))
                .on('error', err => reject(err))
                .on('close', () => resolve())
        })

        await exec(`pk12util -i ${HOME}/badssl.com-client.p12 -d sql:${HOME}/.pki/nssdb -W "badssl.com"`);

        const browser = await puppeteer.launch({
            args: chromium.args,
            defaultViewport: chromium.defaultViewport,
            executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin'),
            headless: chromium.headless,
            ignoreHTTPSErrors: true
        })

        const page = await browser.newPage()
        page.setDefaultTimeout(5000)

        await page.goto('https://client.badssl.com/', { waitUntil: 'networkidle0' })
        const response = await page.content()

        return {
            'statusCode': 200,
            'body': JSON.stringify({
                message: response,
            })
        }
    } catch (err) {
        console.log(err)
        return err
    }
}
```
