### ISSUE TITLE
[BUG] Failed to launch the browser process!

### ISSUE THREAD

**Issue by robbymarston** [Sparticuz/chromium#237]
## Environment

- `chromium` Version: 122.0.0
- `puppeteer` / `puppeteer-core` Version: 22.3.0
- Node.js Version: 20.11.1
- Lambda / GCF Runtime: Node.js 20.x

## Expected Behavior

The browser process should start up normally. 

## Current Behavior

The browser process does not start; instead, throwing the following error:

```
Error: Failed to launch the browser process!
```

## Steps to Reproduce

1. Set up a Lambda function with the following code:

```
import puppeteer from '/opt/node_modules/puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js';
import chromium from '/opt/node_modules/@sparticuz/chromium/build/index.js';

chromium.setHeadlessMode = true;

(async () => {
  try {
    const browser = await puppeteer
      .launch({
        args: chromium.args,
        defaultViewport: chromium.defaultViewport,
        executablePath: await chromium.executablePath(),
        headless: chromium.headless,
      });
    } catch (error) {
      console.error(error);
    }
})();
```

2. Set up an accompanying layer that includes both `puppeteer-core` and `chromium`. 
3. Trigger the function and observe the CloudWatch logs.

**Comment by Sparticuz** [comment]
We don't work in graviton instances, please verify that you are runing in x86

**Comment by robbymarston** [comment]
Thank you for the quick response (and fantastic work) @Sparticuz.  I am using x86. Here's the full template (with ARNs redacted):

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 3
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Layers:
        - <ARN>
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: <ARN>
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  <ARN>
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
```
