### ISSUE TITLE
[BUG] System fonts are not loaded

### ISSUE THREAD

**Issue by Peque** [Sparticuz/chromium#92]
I just migrated:

- From [@sparticuz/chrome-aws-lambda](https://github.com/sparticuz/chrome-aws-lambda) (latest available version 17.1.3)
- To [@Sparticuz/chromium](https://github.com/Sparticuz/chromium) (latest available 19.8.0 with Chrome 112.0.2).

Before, I was able to install the fonts system-wide in the `Dockerfile` with `apt-get install fonts-roboto fonts-open-sans fonts-liberation`, and they were automatically and successfully loaded by Chromium. After the migration, however, the fonts seem not to be loaded.

Is there any identified reason why this is happening or any suggestion on how to fix it?

I'm not using this (nor I was using it) in AWS, but rather in Google Cloud Run, so https://github.com/Sparticuz/chromium/issues/33 does not seem to help.

BTW: Loading with `await chromium.font()` cannot be used since [is not a solution for headers/footers](https://github.com/puppeteer/puppeteer/issues/1853#issuecomment-1083425321).

**Comment by aldenquimby** [comment]
@Peque my team loads fonts as base64 encoded data to get around the header/footer issue:
```css
@font-face {
  font-weight: 400;
  font-family: 'Nunito Sans';
  font-style: normal;
  src: url('data:application/x-font-woff;charset=utf-8;base64,BASE64_BLOB_HERE') format('woff2');
  font-display: swap;
}
```

This has worked for us for years and still works on the latest `@sparticuz/chromium` version
